services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.pem:/localhost.pem
      - ./localhost-key.pem:/localhost-key.pem